"""baslangic semasi

Revision ID: 28cf0e83d46f
Revises: 
Create Date: 2026-10-06 22:38:43.202866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28cf0e83d46f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('aidat_start_period', sa.String(length=7), nullable=True),
    sa.Column('legacy_cutoff_period', sa.String(length=7), nullable=True),
    sa.Column('llm_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_match_threshold', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_site_id'), ['site_id'], unique=False)

    op.create_table('bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('account_no', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iban')
    )
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_account_site_id'), ['site_id'], unique=False)

    op.create_table('block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'name')
    )
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_block_site_id'), ['site_id'], unique=False)

    op.create_table('charge_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('charge_batch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charge_batch_site_id'), ['site_id'], unique=False)

    op.create_table('payer_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('targets', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('confirm_count', sa.Integer(), nullable=False),
    sa.Column('auto_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'normalized_name')
    )
    with op.batch_alter_table('payer_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payer_alias_site_id'), ['site_id'], unique=False)

    op.create_table('period_lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.String(length=7), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_site_id'), ['site_id'], unique=False)

    op.create_table('tariff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('scope_value', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valid_from', sa.String(length=7), nullable=False),
    sa.Column('valid_to', sa.String(length=7), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tariff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tariff_site_id'), ['site_id'], unique=False)

    op.create_table('user_site',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'site_id')
    )
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('bank_code', sa.String(length=30), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batch_file_sha256'), ['file_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_batch_site_id'), ['site_id'], unique=False)

    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=20), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('aidat_start_period', sa.String(length=7), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('legacy_tags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'number')
    )
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_block_id'), ['block_id'], unique=False)

    op.create_table('bank_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('receipt_no', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('payer_name', sa.String(length=300), nullable=True),
    sa.Column('sender_bank', sa.String(length=200), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('category_hint', sa.String(length=20), nullable=True),
    sa.Column('stated_periods', sa.JSON(), nullable=False),
    sa.Column('match_info', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_id'], ['import_batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_transaction_import_id'), ['import_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transaction_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transaction_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transaction_txn_date'), ['txn_date'], unique=False)

    op.create_table('charge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('unique_key', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['charge_batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_key')
    )
    with op.batch_alter_table('charge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charge_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_charge_unit_id'), ['unit_id'], unique=False)

    op.create_table('unit_occupancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit_occupancy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_occupancy_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_occupancy_unit_id'), ['unit_id'], unique=False)

    op.create_table('payment_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['bank_transaction.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_allocation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_allocation_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocation_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocation_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocation_unit_id'), ['unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_allocation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_allocation_unit_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocation_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocation_site_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocation_period'))

    op.drop_table('payment_allocation')
    with op.batch_alter_table('unit_occupancy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_occupancy_unit_id'))
        batch_op.drop_index(batch_op.f('ix_unit_occupancy_person_id'))

    op.drop_table('unit_occupancy')
    with op.batch_alter_table('charge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charge_unit_id'))
        batch_op.drop_index(batch_op.f('ix_charge_site_id'))
        batch_op.drop_index(batch_op.f('ix_charge_period'))

    op.drop_table('charge')
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_transaction_txn_date'))
        batch_op.drop_index(batch_op.f('ix_bank_transaction_status'))
        batch_op.drop_index(batch_op.f('ix_bank_transaction_site_id'))
        batch_op.drop_index(batch_op.f('ix_bank_transaction_import_id'))

    op.drop_table('bank_transaction')
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_block_id'))

    op.drop_table('unit')
    with op.batch_alter_table('import_batch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batch_site_id'))
        batch_op.drop_index(batch_op.f('ix_import_batch_file_sha256'))

    op.drop_table('import_batch')
    op.drop_table('user_site')
    with op.batch_alter_table('tariff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tariff_site_id'))

    op.drop_table('tariff')
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_site_id'))
        batch_op.drop_index(batch_op.f('ix_person_normalized_name'))

    op.drop_table('person')
    op.drop_table('period_lock')
    with op.batch_alter_table('payer_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payer_alias_site_id'))

    op.drop_table('payer_alias')
    with op.batch_alter_table('charge_batch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charge_batch_site_id'))

    op.drop_table('charge_batch')
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_block_site_id'))

    op.drop_table('block')
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_account_site_id'))

    op.drop_table('bank_account')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_site_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    op.drop_table('site')
    op.drop_table('app_user')
    # ### end Alembic commands ###
